"""Agregar campo nombre a usuarios

Revision ID: 85d67f9fd4bd
Revises: 56b178b7a29c
Create Date: 2024-12-27 04:22:27.206741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d67f9fd4bd'
down_revision = '56b178b7a29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False, server_default='Jan Brayan'))

    # Elimina el valor por defecto después de actualizar las filas existentes
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nombre', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('nombre')
    # ### end Alembic commands ###
